-- +goose Up
-- Round 1: identity, sessions, RBAC (role column), audit log, system settings.
-- All timestamps are timestamptz stored in UTC. IDs are UUIDv7 generated by the app.
-- workspace_id is reserved for the future workspace/project scope (ADR-0004) and is
-- always NULL in this phase.

CREATE TABLE system_settings (
    key         text PRIMARY KEY,
    value       jsonb NOT NULL,
    version     integer NOT NULL DEFAULT 1,
    updated_at  timestamptz NOT NULL DEFAULT now(),
    updated_by  uuid
);

CREATE TABLE users (
    id             uuid PRIMARY KEY,
    workspace_id   uuid,
    display_name   text NOT NULL,
    email          text,
    avatar_url     text,
    role           text NOT NULL DEFAULT 'user'
                   CHECK (role IN ('system_admin', 'channel_admin', 'user', 'auditor')),
    status         text NOT NULL DEFAULT 'active'
                   CHECK (status IN ('active', 'disabled')),
    version        integer NOT NULL DEFAULT 1,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    last_login_at  timestamptz
);
CREATE INDEX users_created_at_idx ON users (created_at DESC);
CREATE INDEX users_email_idx ON users (lower(email));

-- External identities (GitHub OAuth2, generic OIDC). One user may link several.
CREATE TABLE user_identities (
    id              uuid PRIMARY KEY,
    user_id         uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    provider        text NOT NULL,          -- provider id, e.g. 'github', 'corp'
    subject         text NOT NULL,          -- immutable id at the provider (GitHub numeric id, OIDC sub)
    login           text,                   -- mutable handle, display only
    email           text,
    email_verified  boolean NOT NULL DEFAULT false,
    created_at      timestamptz NOT NULL DEFAULT now(),
    last_login_at   timestamptz,
    UNIQUE (provider, subject)
);
CREATE INDEX user_identities_user_idx ON user_identities (user_id);

-- Browser sessions. Only the SHA-256 of the session token is stored.
CREATE TABLE sessions (
    id               uuid PRIMARY KEY,
    user_id          uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash       bytea NOT NULL UNIQUE,
    created_at       timestamptz NOT NULL DEFAULT now(),
    last_seen_at     timestamptz NOT NULL DEFAULT now(),
    expires_at       timestamptz NOT NULL,
    user_agent       text NOT NULL DEFAULT '',
    ip_prefix        text NOT NULL DEFAULT '',
    revoked_at       timestamptz,
    revoked_reason   text
);
CREATE INDEX sessions_user_idx ON sessions (user_id) WHERE revoked_at IS NULL;

-- Append-only audit trail. Never stores secrets or full client IPs.
CREATE TABLE audit_logs (
    id             uuid PRIMARY KEY,
    actor_id       uuid,
    actor_name     text,
    action         text NOT NULL,
    resource_type  text NOT NULL,
    resource_id    text,
    ip_prefix      text NOT NULL DEFAULT '',
    request_id     text NOT NULL DEFAULT '',
    metadata       jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_logs_created_idx ON audit_logs (created_at DESC);
CREATE INDEX audit_logs_actor_idx ON audit_logs (actor_id, created_at DESC);
CREATE INDEX audit_logs_action_idx ON audit_logs (action, created_at DESC);

-- +goose Down
DROP TABLE audit_logs;
DROP TABLE sessions;
DROP TABLE user_identities;
DROP TABLE users;
DROP TABLE system_settings;
