-- +goose Up
-- Phase 1 (end): wallets, append-only ledger, balance reservations, redeem codes (ADR-0006/0007/0008).
-- Money columns are bigint nano units of the settlement currency (ADR-0007).
-- IDs are UUIDv7 generated by the app. workspace_id is reserved (always NULL in this phase).

-- One wallet per user, created lazily on first balance change. The wallet row is a
-- cache of the ledger: balance_nano always equals the latest ledger balance_after_nano.
-- Every balance change locks this row (SELECT ... FOR UPDATE) and writes the ledger
-- in the same transaction.
CREATE TABLE wallets (
    id             uuid PRIMARY KEY,
    workspace_id   uuid,
    user_id        uuid NOT NULL UNIQUE REFERENCES users (id),
    balance_nano   bigint NOT NULL DEFAULT 0,
    reserved_nano  bigint NOT NULL DEFAULT 0 CHECK (reserved_nano >= 0),
    version        integer NOT NULL DEFAULT 1,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);

-- Append-only ledger. Corrections are new 'adjust'/'refund' rows, never updates.
CREATE TABLE ledger_entries (
    id                  uuid PRIMARY KEY,
    workspace_id        uuid,
    wallet_id           uuid NOT NULL REFERENCES wallets (id),
    kind                text NOT NULL CHECK (kind IN ('grant', 'charge', 'refund', 'adjust')),
    amount_nano         bigint NOT NULL,          -- positive = credit, negative = debit
    balance_after_nano  bigint NOT NULL,
    ref_type            text NOT NULL CHECK (ref_type IN ('request', 'redeem', 'admin')),
    ref_id              text NOT NULL,
    note                text,
    created_by          uuid,                     -- admin for 'adjust'; NULL otherwise
    created_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ledger_entries_wallet_idx ON ledger_entries (wallet_id, created_at DESC, id DESC);
-- Each gateway request is charged at most once (idempotent settlement).
CREATE UNIQUE INDEX ledger_entries_charge_ref_uidx ON ledger_entries (ref_type, ref_id) WHERE kind = 'charge';

-- Balance held for in-flight gateway requests; released on settlement or expiry.
CREATE TABLE reservations (
    request_id   text PRIMARY KEY,
    wallet_id    uuid NOT NULL REFERENCES wallets (id),
    amount_nano  bigint NOT NULL CHECK (amount_nano > 0),
    created_at   timestamptz NOT NULL DEFAULT now(),
    expires_at   timestamptz NOT NULL
);
CREATE INDEX reservations_expires_idx ON reservations (expires_at);
CREATE INDEX reservations_wallet_idx ON reservations (wallet_id);

-- Redeem code batches. Only 'wallet_credit' exists for now; 'plan' and 'invite'
-- will be added to the CHECK (with their data in payload) in a later migration.
CREATE TABLE redeem_batches (
    id                        uuid PRIMARY KEY,
    workspace_id              uuid,
    kind                      text NOT NULL CHECK (kind IN ('wallet_credit')),
    amount_nano               bigint,
    payload                   jsonb NOT NULL DEFAULT '{}'::jsonb,
    count                     integer NOT NULL CHECK (count > 0),
    max_redemptions_per_code  integer NOT NULL DEFAULT 1 CHECK (max_redemptions_per_code > 0),
    per_user_limit            integer NOT NULL DEFAULT 1 CHECK (per_user_limit > 0),
    valid_from                timestamptz,
    expires_at                timestamptz,
    note                      text,
    status                    text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    created_by                uuid NOT NULL REFERENCES users (id),
    created_at                timestamptz NOT NULL DEFAULT now(),
    updated_at                timestamptz NOT NULL DEFAULT now(),
    version                   integer NOT NULL DEFAULT 1,
    CHECK (kind <> 'wallet_credit' OR amount_nano > 0),
    CHECK (valid_from IS NULL OR expires_at IS NULL OR expires_at > valid_from)
);
CREATE INDEX redeem_batches_created_idx ON redeem_batches (created_at DESC, id DESC);

-- Individual codes. Only the SHA-256 of the normalized code is stored (ADR-0008);
-- prefix ("OG-ABCDE") is for display and support only.
CREATE TABLE redeem_codes (
    id          uuid PRIMARY KEY,
    batch_id    uuid NOT NULL REFERENCES redeem_batches (id),
    code_hash   bytea NOT NULL UNIQUE,
    prefix      text NOT NULL,
    used_count  integer NOT NULL DEFAULT 0 CHECK (used_count >= 0),
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX redeem_codes_batch_idx ON redeem_codes (batch_id);

CREATE TABLE redemptions (
    id               uuid PRIMARY KEY,
    workspace_id     uuid,
    code_id          uuid NOT NULL REFERENCES redeem_codes (id),
    batch_id         uuid NOT NULL REFERENCES redeem_batches (id),
    user_id          uuid NOT NULL REFERENCES users (id),
    ledger_entry_id  uuid REFERENCES ledger_entries (id),
    created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX redemptions_batch_user_idx ON redemptions (batch_id, user_id);
CREATE INDEX redemptions_user_idx ON redemptions (user_id, created_at DESC);
CREATE INDEX redemptions_code_idx ON redemptions (code_id);

-- billing.enforce defaults to false (record charges only, never block requests).
INSERT INTO system_settings (key, value) VALUES ('billing.enforce', '{"enforce": false}'::jsonb)
ON CONFLICT (key) DO NOTHING;

-- +goose Down
DELETE FROM system_settings WHERE key = 'billing.enforce';
DROP TABLE redemptions;
DROP TABLE redeem_codes;
DROP TABLE redeem_batches;
DROP TABLE reservations;
DROP TABLE ledger_entries;
DROP TABLE wallets;
