-- +goose Up
-- Round 4: subscription plans with periodic quotas (ADR-0006, contracts/phase3-api.md §1–§4).
-- IDs are UUIDv7 generated by the app. workspace_id is reserved (always NULL in this phase).
-- Quota amounts (limits, usage) are exact decimals: numeric(38,9) in the database,
-- decimal strings in JSON rule documents.

-- Plans: a set of quota rules + covered logical models + per-period duration.
-- rules/models are JSON documents validated by the app (internal/subscription).
CREATE TABLE plans (
    id               uuid PRIMARY KEY,
    workspace_id     uuid,
    name             text NOT NULL,
    description      text NOT NULL DEFAULT '',
    list_price_nano  bigint CHECK (list_price_nano IS NULL OR list_price_nano >= 0),
    duration         text NOT NULL,                       -- "<n>m|h|d", 1h–366d
    models           jsonb NOT NULL DEFAULT '[]'::jsonb,  -- [] = all models
    rules            jsonb NOT NULL,                      -- QuotaRule[] (1–10)
    stackable        boolean NOT NULL DEFAULT false,
    status           text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),
    created_by       uuid REFERENCES users (id),
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    version          integer NOT NULL DEFAULT 1
);
CREATE INDEX plans_status_idx ON plans (status, created_at DESC, id DESC);

-- A user's plan instance. plan_name/models/rules are snapshots taken at grant time;
-- later plan edits never affect existing subscriptions. 'expired' is derived
-- (now >= ends_at) and never stored.
CREATE TABLE subscriptions (
    id            uuid PRIMARY KEY,
    workspace_id  uuid,
    user_id       uuid NOT NULL REFERENCES users (id),
    plan_id       uuid NOT NULL REFERENCES plans (id),
    plan_name     text NOT NULL,
    models        jsonb NOT NULL DEFAULT '[]'::jsonb,
    rules         jsonb NOT NULL,
    starts_at     timestamptz NOT NULL,
    ends_at       timestamptz NOT NULL,
    status        text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'cancelled')),
    source        text NOT NULL CHECK (source IN ('admin', 'redeem')),
    source_ref    text,                                   -- admin user id / redemption id
    cancelled_at  timestamptz,
    cancelled_by  uuid REFERENCES users (id),
    cancel_note   text,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    version       integer NOT NULL DEFAULT 1,
    CHECK (ends_at > starts_at),
    CHECK (status <> 'cancelled' OR cancelled_at IS NOT NULL)
);
-- Gateway hot path: a user's live subscriptions, earliest-ending first.
CREATE INDEX subscriptions_user_active_idx ON subscriptions (user_id, ends_at) WHERE status = 'active';
CREATE INDEX subscriptions_user_idx ON subscriptions (user_id, created_at DESC, id DESC);
CREATE INDEX subscriptions_plan_active_idx ON subscriptions (plan_id, ends_at) WHERE status = 'active';
CREATE INDEX subscriptions_created_idx ON subscriptions (created_at DESC, id DESC);

-- Quota counters. window_start identifies the window: the calendar/period start,
-- the subscription start (lifetime), the 5-minute bucket start (rolling) or the
-- session start (session). Updated in the settlement transaction.
CREATE TABLE quota_usage (
    subscription_id  uuid NOT NULL REFERENCES subscriptions (id) ON DELETE CASCADE,
    rule_id          text NOT NULL,
    window_start     timestamptz NOT NULL,
    used             numeric(38, 9) NOT NULL DEFAULT 0,
    updated_at       timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (subscription_id, rule_id, window_start)
);

-- One row per gateway request settled against a subscription: makes Record
-- idempotent per request id and keeps the quota charge for reconciliation.
CREATE TABLE subscription_charges (
    request_id         text PRIMARY KEY,
    subscription_id    uuid NOT NULL REFERENCES subscriptions (id) ON DELETE CASCADE,
    model              text NOT NULL,
    quota_charge_nano  bigint NOT NULL DEFAULT 0,
    created_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX subscription_charges_sub_idx ON subscription_charges (subscription_id, created_at DESC);

-- Redeem batches gain kind 'plan' ({planId, periods}). The payload columns must
-- match the kind exactly.
ALTER TABLE redeem_batches DROP CONSTRAINT redeem_batches_kind_check;
ALTER TABLE redeem_batches DROP CONSTRAINT redeem_batches_check;
ALTER TABLE redeem_batches
    ADD COLUMN plan_id uuid REFERENCES plans (id),
    ADD COLUMN periods integer;
ALTER TABLE redeem_batches ADD CONSTRAINT redeem_batches_kind_check CHECK (kind IN ('wallet_credit', 'plan'));
ALTER TABLE redeem_batches ADD CONSTRAINT redeem_batches_payload_check CHECK (
    (kind = 'wallet_credit' AND amount_nano IS NOT NULL AND amount_nano > 0 AND plan_id IS NULL AND periods IS NULL)
    OR (kind = 'plan' AND plan_id IS NOT NULL AND periods IS NOT NULL AND periods BETWEEN 1 AND 120
        AND amount_nano IS NULL)
);
CREATE INDEX redeem_batches_plan_idx ON redeem_batches (plan_id) WHERE plan_id IS NOT NULL;

-- Plan redemptions reference the subscription they created or renewed.
ALTER TABLE redemptions ADD COLUMN subscription_id uuid REFERENCES subscriptions (id);

-- Request logs (partitioned parent; columns propagate to all partitions).
ALTER TABLE request_logs
    ADD COLUMN subscription_id uuid,
    ADD COLUMN quota_charge_nano bigint NOT NULL DEFAULT 0;
CREATE INDEX request_logs_subscription_idx ON request_logs (subscription_id, started_at DESC)
    WHERE subscription_id IS NOT NULL;

-- +goose Down
DROP INDEX request_logs_subscription_idx;
ALTER TABLE request_logs DROP COLUMN quota_charge_nano, DROP COLUMN subscription_id;

ALTER TABLE redemptions DROP COLUMN subscription_id;

-- Plan batches cannot be represented in the previous schema.
DELETE FROM redemptions WHERE batch_id IN (SELECT id FROM redeem_batches WHERE kind = 'plan');
DELETE FROM redeem_codes WHERE batch_id IN (SELECT id FROM redeem_batches WHERE kind = 'plan');
DELETE FROM redeem_batches WHERE kind = 'plan';
DROP INDEX redeem_batches_plan_idx;
ALTER TABLE redeem_batches DROP CONSTRAINT redeem_batches_payload_check;
ALTER TABLE redeem_batches DROP CONSTRAINT redeem_batches_kind_check;
ALTER TABLE redeem_batches DROP COLUMN periods, DROP COLUMN plan_id;
ALTER TABLE redeem_batches ADD CONSTRAINT redeem_batches_kind_check CHECK (kind IN ('wallet_credit'));
ALTER TABLE redeem_batches ADD CONSTRAINT redeem_batches_check CHECK (kind <> 'wallet_credit' OR amount_nano > 0);

DROP TABLE subscription_charges;
DROP TABLE quota_usage;
DROP TABLE subscriptions;
DROP TABLE plans;
